[package]
name = "xiangqi"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
lazy_static = "1.4.0"
num_enum = "0.7.2"
threadpool = "1.8.1"
